name: ezytdl nightly distributable build
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on: 
    schedule:
      - cron: '0 11 * * *' # 6am cst (i'll probably be asleep and have pushed a working change by then)
    workflow_dispatch:

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

  release_tag:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    name: Create release tag

    permissions: write-all

    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
    - uses: actions/checkout@v2
    - name: Get the pre-release tag
      id: get_tag
      run: |
        echo ::set-output name=tag::"$(node -e "console.log(require('./package.json').version)")-nightly.$(git rev-parse --short HEAD)"
        echo ::set-output name=name::"[NIGHTLY] $(node -e "console.log(require('./package.json').version)")-nightly.$(git rev-parse --short HEAD)"
    - name: Create pre-release draft
      id: create_release
      uses: shogo82148/actions-create-release@v1
      with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: ${{ steps.get_tag.outputs.name }}
          commitish: ${{ github.sha }}
          draft: true
          prerelease: true
          make_latest: false

  linux-dist:
    needs: release_tag

    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: '18'

      - name: Install npm deps
        run: |
          npm install

      - name: Build app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run nightly
  macos-dist:
    needs: release_tag
    
    runs-on: macos-latest

    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: '18'

      - name: Install npm deps
        run: |
          npm install

      - name: Build app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.MAC_CERTS }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_KEY }}
        run: |
          npm run nightly
  windows-dist:
    needs: release_tag
    
    runs-on: windows-latest

    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: '18'

      - name: Install npm deps
        run: |
          npm install

      - name: Build app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run nightly
  release:
    needs: [linux-dist, macos-dist, windows-dist, release_tag]
    name: "Release the build"
    runs-on: "ubuntu-latest"

    permissions: write-all

    steps:
    - uses: actions/checkout@v2
    - name: Get the pre-release id
      id: get_tag
      run: |
        echo ::set-output name=tag::"$(git describe --tags --abbrev=0)-nightly.$(git rev-parse --short HEAD)"

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ needs.release_tag.outputs.release_id }}