name: ezytdl uncompressed mac build
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: '18'

      - name: Build app
        run: |
          npm install
          npm run store

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            dist/ezytdl*
            dist/latest*.yml