name: ezytdl distributable build
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: '18'

      - name: Install npm deps
        run: |
          npm install

      - if: ${{ matrix.os }} == 'ubuntu-latest'
        name: Install flatpak & flatpak builder (ubuntu only)
        run: |
          sudo apt update
          sudo apt install flatpak flatpak-builder -y

      - name: Build app
        run: |
          npm run dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            dist/ezytdl*
            dist/latest*.yml