name: ezytdl distributable build
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on: workflow_dispatch

jobs:
  linux-dist:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: '18'

      - name: Install npm deps
        run: |
          npm install

      - name: Build app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist
  macos-dist:
    runs-on: macos-latest

    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: '18'

      - name: Install npm deps
        run: |
          npm install

      - name: Build app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.MAC_CERTS }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_KEY }}
        run: |
          npm run dist
  windows-dist:
    runs-on: windows-latest

    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: '18'

      - name: Install npm deps
        run: |
          npm install

      - name: Build app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist