name: ezytdl distributable build
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on: workflow_dispatch

jobs:
  linux-dist:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: '18'
      
      #- name: Install python
      #  uses: actions/setup-python@v4
      #  with:
      #    python-version: '3.11.3'
      #    cache: 'pip'

      - name: Install python (apt)
        run: |
          sudo apt-get install python3.11

      - name: Install npm deps
        run: |
          npm install

      - name: Build app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist
  macos-dist:
    runs-on: macos-latest

    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: '18'
      
      #- name: Install python
      #  uses: actions/setup-python@v4
      #  with:
      #    python-version: '3.11.3'
      #    cache: 'pip'

      - name: Install python (brew)
        run: |
          brew install python@3.11

      - name: Install npm deps
        run: |
          npm install

      - name: Build app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.MAC_CERTS }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_KEY }}
        run: |
          npm run dist
  windows-dist:
    runs-on: windows-latest

    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: '18'
      
      #- name: Install python
      #  uses: actions/setup-python@v4
      #  with:
      #    python-version: '3.11.3'
      #    cache: 'pip'

      - name: Install python (choco)
        run: |
          choco install python --version 3.11.3

      - name: Install npm deps
        run: |
          npm install

      - name: Build app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist