name: mac build
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on: [push, pull_request]

jobs:
  macos:
    runs-on: "macos-latest"

    permissions:
      contents: read

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CSC_LINK: ${{ secrets.MAC_CERTS }}
      CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install ffmpeg (macos only)
        uses: FedericoCarboni/setup-ffmpeg@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: "18"

      - name: Install npm deps
        run: |
          npm install

      - name: Test from source
        run: |
          npm start -- --testrun

      - name: Run uncompressed (store) build
        run: |
          npm run store

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            dist/ezytdl*
            dist/latest*.yml
