name: linux build
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on: [push, pull_request, workflow_dispatch]

jobs:
  linux:
    runs-on: "ubuntu-20.04"

    permissions:
      contents: read

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v1

      - name: install deps
        run: |
          sudo apt update -y
          sudo apt install -y libvips

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: "18"

      - name: Install npm deps
        run: |
          npm install

      - name: Run uncompressed (store) build
        run: |
          npm run store
      
      - name: testrun compiled build
        continue-on-error: true
        run: |
          npm run test
          echo " --- COMPLETED TESTRUN, BELOW IS THE RESULT ---"
          echo $TESTS_PASSED

      - name: fail if "TESTS_PASSED" not true
        if: ${{ env.TESTS_PASSED }} != 'true'
        run: exit 1
