name: windows
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on: [push, pull_request]

jobs:
  win:
    runs-on: "windows-latest"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: "18"

      - name: Install npm deps
        run: |
          npm install

      - name: Test from source
        run: |
          npm start -- --testrun

      - name: Run uncompressed (store) build
        run: |
          npm run store
