name: ezytdl auto test-run (using store compression)
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: '18'

      - if: ${{ matrix.os }} == 'macos-latest'
        name: Install ffmpeg from homebrew (macos only)
        run: |
          brew install ffmpeg

      - name: Test from source
        run: |
          npm start -- --testrun

      - name: Run uncompressed (store) build
        run: |
          npm run store